name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        
    - name: Install dependencies
      run: task install
      
    - name: Run code quality checks
      run: task check
      
    - name: Run unit tests
      run: task test:unit
      
    - name: Run integration tests (no network/private keys)
      run: task test:integration
      env:
        # Skip tests requiring actual network or private keys in CI
        SKIP_LIVE_TESTS: "true"

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        
    - name: Install dependencies
      run: task install
      
    - name: Run security audit
      run: task audit
      continue-on-error: true  # Don't fail CI for advisory issues

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        
    - name: Build package
      run: task package
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-packages
        path: dist/
        retention-days: 7